### ISSUE TITLE
Add Windows build

### ISSUE THREAD

**Issue by isuruf** [conda-forge/libflint-feedstock#1]
This requires changes made after the last release.

**Comment by saraedum** [comment]
What is needed here?

**Comment by isuruf** [comment]
For upstream to make a release. I fixed a bunch of stuff for windows, but they haven't released in 4 years.

**Comment by saraedum** [comment]
I see, so https://github.com/wbhart/flint2/issues/517 for future reference.

**Comment by isuruf** [comment]
Done with 2.6.0
