### ISSUE TITLE
flint 3.0.0 is out

### ISSUE THREAD

**Issue by videlec** [conda-forge/libflint-feedstock#28]
### Comment:

Flint 3.0.0 has been released [see anouncement](https://groups.google.com/g/flint-devel/c/pDVgut-EOoI). Starting from version 3.0.0 flint contains arb and antic that used to have their own conda packaging ([arb-feedstock](https://github.com/conda-forge/arb-feedstock) and [antic-feedstock](https://github.com/conda-forge/antic-feedstock)).

**Comment by saraedum** [comment]
Fixed in #29
